spring:
  main:
    web-application-type: none
    banner-mode: off
    allow-bean-definition-overriding: true
  application:
    name: neighbor-notebook
  jmx:
    enabled: false

app:
  version: 0.0.1
  storage:
    path: ${user.home}/neighbor-notebook/notes
  window:
    title: Neighbor Notebook
    width: 800
    height: 600
